version: "3"
services:
  numbersaver:
    build: .
    depends_on: 
      - postgres
    environment:
      - DATABASE_URL=postgres://postgres:password@postgres:5432/postgres
  
    ports: 
      - 9000:3000
    
  postgres:
    image: postgres
  
    container_name:  postgres
    expose:
      - "5432"
    environment:
      POSTGRES_PASSWORD: password  

 

    